src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
class Formation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    /**
     * @var Collection<int, Session>
     */
    #[ORM\OneToMany(targetEntity: Session::class, mappedBy: 'formation', orphanRemoval: true, cascade:['persist'])]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->setFormation($this);
        }

        return $this;
    }

    public function removeSession(Session $session): static
    {
        if ($this->sessions->removeElement($session)) {
            // set the owning side to null (unless already changed)
            if ($session->getFormation() === $this) {
                $session->setFormation(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
    return $this->title;
    }

    
}

src/Entity/Stagiaire.php
<?php

namespace App\Entity;

use App\Repository\StagiaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StagiaireRepository::class)]
class Stagiaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $firstName = null;

    #[ORM\Column(length: 100)]
    private ?string $lastName = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $birthday = null;

    #[ORM\Column(length: 30)]
    private ?string $sexe = null;

    #[ORM\Column(length: 100)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $phoneNumber = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    /**
     * @var Collection<int, Session>
     */
    #[ORM\ManyToMany(targetEntity: Session::class, mappedBy: 'stagiaires', orphanRemoval: true, cascade:['persist'])]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getBirthday(): ?\DateTime
    {
        return $this->birthday;
    }

    public function getBirthdayFr(): ?string {
        return $this->birthday->format("d-m-Y");
    }

    public function setBirthday(\DateTime $birthday): static
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): static
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(int $phoneNumber): static
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->addStagiaire($this);
        }

        return $this;
    }

    public function removeSession(Session $session): static
    {
        if ($this->sessions->removeElement($session)) {
            $session->removeStagiaire($this);
        }

        return $this;
    }

    public function __toString() {
        return "" . $this->getFirstName() . " " . $this->getLastName() . "";
    }
}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('description', TextareaType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('valider', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary']
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Entity\Formation;
use App\Entity\Programme;
use App\Entity\Stagiaire;
use App\Form\SessionType;
use App\Form\FormationType;
use App\Form\StagiaireType;
use App\Repository\SessionRepository;
use App\Repository\FormationRepository;
use App\Repository\ProgrammeRepository;
use App\Repository\StagiaireRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

final class FormationController extends AbstractController
{
    //Fonction pour lister les formations
    #[Route('/formation', name: 'app_formation')]
    public function index(FormationRepository $formationRepository): Response
    {
        //La variable formations est un tableau qui va se remplir avec les données du tableau formation en base de données grâce au repository Formation
        $formations = $formationRepository->findBy([], ['title' => 'ASC']);

        return $this->render('formation/index.html.twig', [
            'formations' => $formations,
        ]);
    }

    //La fonction va permettre de créer un formulaire et si c'est pour ajouter une formation, alors le formulaire sera vide, mais si c'est pour modifier un module existant le formulaire sera pré-remplit
    #[Route('/formation/add', name: 'add_formation')]
    #[Route('/formation/{id}/edit', name: 'edit_formation')]
    public function add_editFormation(Formation $formation = null, Request $request, EntityManagerInterface $entityManager): Response
    {

        if(!$formation) {
            $formation = new Formation();
        }

        $form = $this->createForm(FormationType::class, $formation);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $formation = $form->getData();

            $entityManager->persist($formation);

            $entityManager->flush();

            return $this->redirectToRoute('app_formation');
        }

        return $this->render('formation/add.html.twig', [
            'formAddFormation' => $form->createView(),
            'edit' => $formation->getId()
        ]);
    }

    //Fonction de suppression d'une formation
    #[Route('/formation/{id}/delete', name: 'delete_formation')]
    public function deleteFormation(Formation $formation, EntityManagerInterface $entityManager) {
        $entityManager->remove($formation);
        $entityManager->flush();

        return $this->redirectToRoute('app_formation');
    }

    //Fonction qui va afficher le détail d'une formation
    #[Route('/formation/{id}', name: 'show_formation')]
    public function showFormation(Formation $formation, Session $session, SessionRepository $sessionRepository, EntityManagerInterface $entityManager): Response {
        
        $sessions = $sessionRepository->findByFormation($formation->getId());

        return $this->render('formation/show.html.twig', [
            'formation' => $formation,
            'sessions' => $sessions,
        ]);
    }

    #[Route('/session/add', name: 'add_session')]
    #[Route('/session/{id}/edit', name: 'edit_session')]
    public function add_editSession(Session $session = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        if(! $session) {
            $session = new Session();
        }

        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            
            $session = $form->getData();

            $entityManager->persist($session);

            $entityManager->flush();

            return $this->redirectToRoute('app_formation');
        }

        return $this->render('formation/addSession.html.twig', [
            'formAddSession' => $form->createView(),
            'edit' => $session->getId(),
        ]);
    }

    #[Route('/session/{id}/delete', name: 'delete_session')]
    public function deleteSession(Session $session, EntityManagerInterface $entityManager)
    {
        $entityManager->remove($session);

        $entityManager->flush();

        return $this->redirectToRoute('app_formation');
    }

    //Fonction qui va afficher le détail d'une session
    #[Route('/session/{id}/show', name: 'show_session')]
    public function showSession(Session $session, Programme $programme, ProgrammeRepository $programmeRepository, EntityManagerInterface $entityManager): Response 
    {
        $programmes = $programmeRepository->findBySession($session->getId());

        $stagiaires = $session->getStagiaires();

        return $this->render('formation/showSession.html.twig', [
            'session' => $session,
            'programmes' => $programmes,
            'stagiaires' => $stagiaires,
        ]);
    }

    #[Route('/stagiaire', name: 'app_stagiaire')]
    public function appStagiaire(StagiaireRepository $stagiaireRepository) : Response
    {
        $stagiaires = $stagiaireRepository->findBy([], ['lastName' => 'ASC']);

        return $this->render('formation/listStagiaire.html.twig', [
            'stagiaires' => $stagiaires,
        ]);
    }

    #[Route('/stagiaire/add', name: 'add_stagiaire')]
    #[Route('/stagiaire/{id}/edit', name: 'edit_stagiaire')]
    public function add_editStagiaire(Stagiaire $stagiaire = null, Request $request, EntityManagerInterface $entityManager) :Response
    {

        if(! $stagiaire) {
            $stagiaire = new Stagiaire;
        }

        $form = $this->createForm(StagiaireType::class, $stagiaire);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $stagiaire = $form->getData();
            $entityManager->persist($stagiaire);
            $entityManager->flush();

            return $this->redirectToRoute('app_stagiaire');
        }

        return $this->render('formation/addStagiaire.html.twig', [
            'formAddStagiaire' => $form->createView(),
            'edit' => $stagiaire->getId(),
        ]);
    }

    #[Route('/stagiaire/{id}/delete', name: 'delete_stagiaire')]
    public function deleteStagiaire(Stagiaire $stagiaire, EntityManagerInterface $entityManager) 
    {
            $entityManager->remove($stagiaire);
            $entityManager->flush();

            return $this->redirectToRoute('app_stagiaire');
    }

    #[Route('/stagiaire/{id}', name: 'show_stagiaire')]
    public function showStagiaire(Stagiaire $stagiaire, StagiaireRepository $stagiaireRepository, EntityManagerInterface $entityManager) : Response
    {
        
        return $this->render('formation/showStagiaire.html.twig', [
            'stagiaire' => $stagiaire,
        ]);
    }
}

templates/formation/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification aux Formations{% endblock %}

{% block body %}
    {% if edit %}
        <h1>Editer une formation</h1>
    {% else %}
        <h1>Ajouter une formation</h1>
    {% endif %}

    {{ form_start(formAddFormation) }}

    <div class="my-custom-class-for-errors">
        {{ form_errors(formAddFormation) }}
    </div>

    <div class="row">
        <div class="col-sm">
            {{ form_row(formAddFormation.title) }}
        </div>
        <div class="col-sm">
            {{ form_row(formAddFormation.description) }}
        </div>
    </div>
            {{ form_row(formAddFormation.valider) }}

    {{ form_end(formAddFormation) }}

{% endblock %}

templates/formation/addSession.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification aux Sessions{% endblock %}

{% block body %}
    {# {% if edit %} #}
        {# <h1>Editer une formation</h1>
    {% else %} #}
        <h1>Ajouter une session</h1>
    {# {% endif %} #}

    {{ form_start(formAddSession) }}
    {# {{ form_widget(formAddEmploye) }} #}

    <div class="my-custom-class-for-errors">
        {{ form_errors(formAddSession) }}
    </div>

    <div class="row">
        <div class="col-sm">
            {{ form_row(formAddSession.startDate) }}
            {{ form_row(formAddSession.endDate) }}
        </div>
        <div class="col-sm">
            {{ form_row(formAddSession.capacityNumber) }}
            {{ form_row(formAddSession.reservedPlaces) }}
        </div>
        <div class="col-sm">
            {{ form_row(formAddSession.formation) }}
        </div>
        <div class="col-sm">
            {{ form_row(formAddSession.stagiaires) }}
        </div>
    </div>
            {{ form_row(formAddSession.valider) }}

    {{ form_end(formAddSession) }}

{% endblock %}

templates/formation/addStagiaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification aux Stagiaires{% endblock %}

{% block body %}
    {# {% if edit %} #}
        {# <h1>Editer une formation</h1>
    {% else %} #}
        <h1>Ajouter un stagiaire</h1>
    {# {% endif %} #}

    {{ form_start(formAddStagiaire) }}
    {# {{ form_widget(formAddEmploye) }} #}

    <div class="my-custom-class-for-errors">
        {{ form_errors(formAddStagiaire) }}
    </div>

    <div class="row">
        <div class="col-sm">
            {{ form_row(formAddStagiaire.firstName) }}
            {{ form_row(formAddStagiaire.lastName) }}
        </div>
        <div class="col-sm">
            {{ form_row(formAddStagiaire.birthday) }}
        </div>
        <div class="col-sm">
            {{ form_row(formAddStagiaire.sexe) }}
        </div>
        <div class="col-sm">
            {{ form_row(formAddStagiaire.city) }}
        </div>
        <div class="col-sm">
            {{ form_row(formAddStagiaire.email) }}
            {{ form_row(formAddStagiaire.phoneNumber) }}
        </div>
        <div class="col-sm">
            {{ form_row(formAddStagiaire.picture) }}
        </div>
        <div class="col-sm">
            {{ form_row(formAddStagiaire.sessions) }}
        </div>
    </div>
            {{ form_row(formAddStagiaire.valider) }}

    {{ form_end(formAddStagiaire) }}

{% endblock %}

templates/formation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des formations{% endblock %}

{% block body %}

<div class="wrapper">
    <h1>Liste des formations</h1>
    <div class="list">
    {% for formation in formations %}
        <a href="{{ path('show_formation', {'id':formation.id}) }}">{{ formation }}</a> <a href="{{ path('delete_formation', {'id':formation.id}) }}">Supprimer</a> <br>        
    {% endfor %}
    </div>

    <a href=" {{ path('add_formation') }}">Ajouter Formations</a>
</div>
{% endblock %}

templates/formation/listStagiaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des stagiaires{% endblock %}

{% block body %}

<div class="wrapper">
    <h1>Liste des stagiaires</h1>
    <div class="listStagiaire">
    {% for stagiaire in stagiaires %}
        <a href="{{ path('show_stagiaire', {'id': stagiaire.id}) }}">{{ stagiaire }}</a> <a href="{{ path('edit_stagiaire', {'id':stagiaire.id}) }}">Editer</a> <a href="{{ path('delete_stagiaire', {'id':stagiaire.id}) }}">Supprimer</a> <br>        
    {% endfor %}
    </div>

    <a href=" {{ path('add_stagiaire') }}">Ajouter stagiaire</a>
</div>
{% endblock %}

templates/formation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail de la formation{% endblock %}

{% block body %}

<div class="wrapper">
    <h1>Détail de la formation</h1>
    <article class="info-formation">

        <h2>{{ formation }}</h2>

        <p>{{ formation.description }}</p>

    </article>
    <p>Vous souhaitez modifier le titre ou la description ? </p>
    <a href="{{ path('edit_formation', {'id':formation.id}) }}">Editer</a>
</div>


<div class="containerSession">
    <h2>Liste des sessions</h2>

    <div class="listSession">
    {% for session in sessions %}
        <a href="{{ path('show_session', {'id':session.id}) }}">{{ session }}</a> <a href="{{ path('edit_session', {'id':session.id}) }}">Editer</a> <a href="{{ path('delete_session', {'id':session.id}) }}">Supprimer</a><br>
    {% endfor %}
    </div>

    <p>Ajouter une session</p>
    <a href="{{ path('add_session') }}">Ajouter</a>


</div>
{% endblock %}

templates/formation/showSession.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail de la session{% endblock %}

{% block body %}

<div class="wrapper">
    <h1>Détail de la session</h1>
    <article class="info-formation">

        <h2>{{ session }}</h2>
        
        <p>Vous pouvez retrouver ci-dessous le programme de la session, donc la liste des modules et leurs durée en jours. Ainsi que la liste des stagiaires. </p>
    </article>

    <div class="listModule">
    <h3>Liste des modules de la session</h3>
        
    {% for programme in programmes %}
        <p><a href="{{ path('show_module', {'id':programme.module.id}) }}">{{ programme }}</a> qui durera {{programme.duration}} Jours</p><br>
    {% endfor %}
    </div>


    <div class="listStagiaire">
    <h3>Liste des stagiaires de la session</h3>

    {% for stagiaire in stagiaires %}
        <p><a href="{{ path('show_stagiaire', {'id': stagiaire.id}) }}">{{ stagiaire }}</a>, née le {{ stagiaire.birthdayFr }}</p><br>
    {% endfor %}
    </div>

</div>
{% endblock %}

templates/formation/showStagiaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'un stagiaire{% endblock %}

{% block body %}

<div class="wrapper">
    <h1>Détail d'un stagiaire</h1>
    <article class="info-formation">

        <h2>{{ stagiaire }}</h2>

        <p>Date de naissance : {{ stagiaire.birthdayFr }}</p>
        <p>Ville : {{ stagiaire.city }}</p>
        <p>E-mail : {{ stagiaire.email }}</p>
        <p>Numéro de téléphone : {{ stagiaire.phoneNumber }}</p>

    </article>
    <p>Vous souhaitez modifier les données sur un stagiaire ? </p>
    {# <a href="{{ path('edit_stagiaire', {'id':stagiaire.id}) }}">Editer</a> #}
</div>

{% endblock %}